### ISSUE TITLE
Wait instruction cycle 

### ISSUE THREAD

**Issue by jagjordi** [silagokth/SiLagoDoc#1]
WAIT instruction waits cycle+1
if cycle 0 the instruction behaves like a nop
if cycle > 0 it waits for cycle+1

**Comment by herenvarno** [comment]
This is not the intended behavior.
WAIT cycles=0 should signal the end of computation epoch so that the global controller can know every cell has signaled RETUEN.
WAIT cycle=n will delay n cycles, including the cycle that issues the WAIT instruction.

**Comment by jagjordi** [comment]
Why not have dedicated HALT instruction?
