### ISSUE TITLE
BRN instruction

### ISSUE THREAD

**Issue by herenvarno** [silagokth/SiLagoDoc#5]
Currently, BRN has the following format:

```
brn (reg=??, target=??)
```
It branches to pc+target if reg is true.

To implement unconditional branch, we need maintain a boolean register that is always 1.

What if we redesign the brn instruction as:

```
brn (reg=??, true_target=??, false_target=??)
```
It branches to pc+true_target if reg is true, otherwise, branch to pc+false_target.

unconditional branch can be implemented by setting true_target=false_target, the reg field is irrelevant.

This way, IF-THEN-ELSE structure is also easier because it naturally support both true and false direction.

What will be the HW implication if we design like this?

**Comment by jagjordi** [comment]
this is good, it Mayes very simple the hardware, just a mmux controlled by the boolean registrar that closed true or false increment to be added to PC.

Best regards,

Jordi Altayó
________________________________

**Comment by herenvarno** [comment]
Done
